version: "2"
services:
  etcd:
    image: "quay.io/coreos/etcd:v2.3.8"
    ports:
      - "4001:4001"
      - "2380:2380"
      - "2379:2379"
    command:
      -name etcd0
      -advertise-client-urls "http://etcd:2379,http://etcd:4001"
      -listen-client-urls "http://0.0.0.0:2379,http://0.0.0.0:4001"
      -initial-advertise-peer-urls http://${HostIP}:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster "etcd0=http://${HostIP}:2380"
      -initial-cluster-state new

  rabbit:
    image: "rabbitmq"
    ports:
        - "4369:4369"
        - "5671:5671"
        - "5672:5672"
        - "15672:15672"

  kafka:
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
    image: "teivah/kafka"
    ports:
      - "2181:2181"
      - "9092:9092"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"